Update 6.yml

diff --git a/.github/workflows/6.yml b/.github/workflows/6.yml
--- a/.github/workflows/6.yml
+++ b/.github/workflows/6.yml
@@ -45,7 +45,9 @@ jobs:
           df -h
           sudo docker system prune -af || true
           sudo apt clean
-          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
+          sudo mv /usr/share/dotnet /usr/share/dotnet.bak
+          sudo mv /usr/local/lib/android /usr/local/lib/android.bak
+          sudo mv /opt/ghc /opt/ghc.bak
           echo "== 清理后磁盘使用情况 =="
           df -h
 
@@ -63,7 +65,7 @@ jobs:
             libreadline-dev libssl-dev libtool libyaml-dev libz-dev lld llvm lrzsz mkisofs msmtp nano \
             ninja-build p7zip p7zip-full patch pkgconf python3 python3-pip python3-ply python3-docutils \
             python3-pyelftools qemu-utils re2c rsync scons squashfs-tools subversion swig texinfo uglifyjs \
-            upx-ucl unzip vim wget xmlto xxd zlib1g-dev zstd
+            upx-ucl unzip vim wget xmlto xxd zlib1g-dev zstd xh
 
       - name: 创建工作目录
         run: |
@@ -74,7 +76,8 @@ jobs:
       - name: 下载并解压官方工具链
         run: |
           TOOLCHAIN_URL="https://downloads.openwrt.org/snapshots/targets/rockchip/armv8/openwrt-toolchain-rockchip-armv8_gcc-14.4.0_musl.Linux-x86_64.tar.zst"
-          curl -fL --retry 3 --retry-delay 5 -o /tmp/toolchain.tar.zst "$TOOLCHAIN_URL"
+##          curl -fL --retry 3 --retry-delay 5 -o /tmp/toolchain.tar.zst "$TOOLCHAIN_URL"
+          xh -d "$TOOLCHAIN_URL" -o /tmp/toolchain.tar.zst
           
           [ -s /tmp/toolchain.tar.zst ] || { echo "❌ 工具链下载失败"; exit 1; }
           
@@ -138,9 +141,11 @@ jobs:
         working-directory: ${{ env.OPENWRT_DIR }}
         run: |
           rm -f feeds.conf.default
-          curl -fL --retry 3 -o feeds.conf.default \
-            https://github.com/immortalwrt/immortalwrt/raw/refs/heads/master/feeds.conf.default
-          [ -s feeds.conf.default ] || { echo "❌ feeds.conf.default 下载失败"; exit 1; }
+##          curl -fL --retry 3 -o feeds.conf.default \
+##            https://github.com/immortalwrt/immortalwrt/raw/refs/heads/master/feeds.conf.default
+##          [ -s feeds.conf.default ] || { echo "❌ feeds.conf.default 下载失败"; exit 1; }
+          xh -d https://github.com/immortalwrt/immortalwrt/raw/refs/heads/master/feeds.conf.default
+          ls feeds.conf.default
 
       - name: 更新并安装 feeds
         working-directory: ${{ env.OPENWRT_DIR }}
